package bingChatAi

func GetExact() string {
	return "{\n  \"arguments\": [\n    {\n      \"source\": \"cib\",\n      \"optionsSets\": [\n        \"nlu_direct_response_filter\",\n        \"deepleo\",\n        \"enablemm\",\n        \"h3precise\",\n        \"nocache\",\n        \"nointernalsugg\",\n        \"nourldedupe\",\n        \"healthansgnd\",\n        \"travelansgnd\",\n        \"dv3sugg\",\n        \"clgalileo\"\n      ],\n      \"allowedMessageTypes\": [\n        \"Chat\"],\n      \"sliceIds\": [],\n      \"verbosity\": \"verbose\",\n      \"traceId\": \"\",\n      \"isStartOfSession\": false,\n      \"message\": {\n        \"locale\": \"de-DE\",\n        \"market\": \"de-DE\",\n        \"region\": \"CH\",\n        \"location\": \"\",\n        \"locationHints\": [],\n        \"timestamp\": \"\",\n        \"author\": \"user\",\n        \"inputMethod\": \"Keyboard\",\n        \"text\": \"\",\n        \"messageType\": \"Chat\"\n      },\n      \"conversationSignature\": \"\",\n      \"participant\": {\n        \"id\": \"\"\n      },\n      \"conversationId\": \"\"\n    }\n  ],\n  \"invocationId\": \"\",\n  \"target\": \"chat\",\n  \"type\": 4\n}"
}

func GetNormal() string {
	return "{\n  \"arguments\": [\n    {\n      \"source\": \"cib\",\n      \"optionsSets\": [\n        \"nlu_direct_response_filter\",\n        \"deepleo\",\n        \"enablemm\",\n        \"galileo\",\n        \"nocache\",\n        \"nointernalsugg\",\n        \"nourldedupe\",\n        \"healthansgnd\",\n        \"travelansgnd\",\n        \"dv3sugg\",\n        \"dlwebtrunc\",\n        \"glpromptv6\"\n      ],\n      \"allowedMessageTypes\": [\n        \"Chat\"],\n      \"sliceIds\": [],\n      \"verbosity\": \"verbose\",\n      \"traceId\": \"\",\n      \"isStartOfSession\": false,\n      \"message\": {\n        \"locale\": \"de-DE\",\n        \"market\": \"de-DE\",\n        \"region\": \"CH\",\n        \"location\": \"\",\n        \"locationHints\": [],\n        \"timestamp\": \"\",\n        \"author\": \"user\",\n        \"inputMethod\": \"Keyboard\",\n        \"text\": \"\",\n        \"messageType\": \"Chat\"\n      },\n      \"conversationSignature\": \"\",\n      \"participant\": {\n        \"id\": \"\"\n      },\n      \"conversationId\": \"\"\n    }\n  ],\n  \"invocationId\": \"\",\n  \"target\": \"chat\",\n  \"type\": 4\n}"
}

func GetCreative() string {
	return "{\n  \"arguments\": [\n    {\n      \"source\": \"cib\",\n      \"optionsSets\": [\n        \"nlu_direct_response_filter\",\n        \"deepleo\",\n        \"enablemm\",\n        \"h3imaginative\",\n        \"nocache\",\n        \"nointernalsugg\",\n        \"nourldedupe\",\n        \"healthansgnd\",\n        \"travelansgnd\",\n        \"dv3sugg\",\n        \"clgalileo\",\n        \"gencontentv3\"\n      ],\n      \"allowedMessageTypes\": [\n        \"Chat\"],\n      \"sliceIds\": [],\n      \"verbosity\": \"verbose\",\n      \"traceId\": \"\",\n      \"isStartOfSession\": false,\n      \"message\": {\n        \"locale\": \"de-DE\",\n        \"market\": \"de-DE\",\n        \"region\": \"CH\",\n        \"location\": \"\",\n        \"locationHints\": [],\n        \"timestamp\": \"\",\n        \"author\": \"user\",\n        \"inputMethod\": \"Keyboard\",\n        \"text\": \"\",\n        \"messageType\": \"Chat\"\n      },\n      \"conversationSignature\": \"\",\n      \"participant\": {\n        \"id\": \"\"\n      },\n      \"conversationId\": \"\"\n    }\n  ],\n  \"invocationId\": \"\",\n  \"target\": \"chat\",\n  \"type\": 4\n}"
}
